site_name: M.I.L.F.
site_url: https://mathiasgarnier.github.io/MILF/
site_description: Sur ce petit blog, je vous parle de tout ce que j’apprends dans l’optique de faire un assistant de preuve et des “mathématiques embarquées” !
site_author: Garnier Mathias

theme:
  name: material
  language: fr

#plugins:
#  - blog

#markdown_extensions:
#  - pymdownx.arithmatex:
#      generic: true

extra_javascript:
  #- javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://mysite/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - docs/extra.js
